"""added a dateposted field

Revision ID: 280ae3393be1
Revises: 
Create Date: 2020-03-29 20:23:06.877891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280ae3393be1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date_posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'date_posted')
    # ### end Alembic commands ###
